### ISSUE TITLE
patched HD4000 weird behavior

### ISSUE THREAD

**Issue by ArsBinarii** [toleda/graphics_Intel_framebuffers#3]
hey, 
patched the AppleIntelFramebufferCapri to get VGA on 10.12.2. 
First weird thing: was targeting 0B006601 and moded the connectors, now all platform ids have VGA
Second weird thing: 0B006601 will result in black screen or reboot
Third weird thing: VGA with 03006601 is vibrating (higher refresh results in higher vibrating) - only one I can boot and have Metal

**Comment by toleda** [comment]
macOS does not support VGA connectors, use an adapter off a supported HDMI, DVI or DP port.

**Comment by ArsBinarii** [comment]
sorry got the wrong owner of the patch...sorry. But here is a good read: http://forum.osxlatitude.com/index.php?/topic/2945-guide-for-enabling-vga-and-hdmi-in-intel-hd4000-gpu/ if you are interested. 

Can be closed.
